 version: '3.1'
 services:
   rabbitmq:
     image: rabbitmq:3.11.8-management
     container_name: rabbitmq
     restart: always
     hostname: rabbitmq
     environment:
       RABBITMQ_DEFAULT_VHOST: rabbitmq_vhost
       RABBITMQ_DEFAULT_USER: rabbitmq
       RABBITMQ_DEFAULT_PASS: rabbitmq
     ports:
       - "5672:5672"
       - "15672:15672"
     volumes:
       - ./data:/var/lib/rabbitmq
