version: '3.1'  
  
services:  
  mysql:  
    image: mysql:${MYSQL_VERSION:-8.0.39} 
    restart: always  
    environment:  
      MYSQL_USER: ${MYSQL_USER:-mysql}  
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mysql}  
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-mysql}  
    ports:  
      - "${MYSQL_PORT:-3306}:3306"
