version: '3.1'  
  
services:  
  mysql:  
    image: ${MYSQL_IMAGE:-mysql:8.0.39} 
    restart: always  
    environment:  
      MYSQL_USER: ${MYSQL_USER:-mysql}  
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mysql}  
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-mysql}
      TZ: ${MYSQL_TZ:-UTC}
    ports:  
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - "${MYSQL_DATA_PATH:-./mysql}:/var/lib/mysql"
